

GET http://localhost:4000/getusers

#####

GET http://localhost:4000/user-api/getusers/2
#####


POST http://localhost:4000/user-api/create-user
Content-Type: application/json

{
    "id":3,
    "name":"kiran",
    "age":24

}



#####


PUT http://localhost:4000/user-api/update-user
Content-Type: application/json

{
    "id":1,
    "name":"kirti",
    "age":17

}


####


DELETE http://localhost:4000/user-api/remove-user/1
####

GET http://localhost:4000/product-api/getproduct

#####

GET http://localhost:4000/product/getproducts
#####